# Flow Control Statement 
- Decision making
    - if
    - elif
    - else
- loop  
    - while loop
    - for loop

# Loop in data strucures

## 1.List

In [1]:
l=[1,3,4,"spain"]

In [4]:
for i in l:
    print(i)

1
3
4
spain


In [5]:
for i in l:
    print(i,end=" ")

1 3 4 spain 

## 2. string

In [6]:
a="PYTHON"

In [7]:
for i in a:
    print(i)

P
Y
T
H
O
N


In [11]:
for i in a:
    print(i,end="")

PYTHON

## 3.Tuple

In [12]:
b=(2,4,6,7)

In [14]:
for i in b:
    print(i)

2
4
6
7


## 4. Dictionary

In [15]:
dict={"name":"Vineet kumar","Age":23,"Gender":"Male","Phone_no":6397550313}

In [16]:
for i in dict:
    print(i)

name
Age
Gender
Phone_no


In [19]:
for k,v in dict.items():
    print(k)
    print(v)

name
Vineet kumar
Age
23
Gender
Male
Phone_no
6397550313


In [20]:
dict1={"UP":"Lucknow","BR":"Patna","DL":"Delhi","MH":"Mumbai"}

In [21]:
for k,v in dict1.items():
    print(k +":"+v)

UP:Lucknow
BR:Patna
DL:Delhi
MH:Mumbai


In [23]:
for i in dict1:
    print(i +":"+ dict1[i])

UP:Lucknow
BR:Patna
DL:Delhi
MH:Mumbai


## 5. Array

In [24]:
import numpy as np

In [25]:
height=np.array([23,45,67,89])

In [26]:
for i in height:
    print(i)

23
45
67
89


In [27]:
cricket=np.array([
    [23,56],
    [33,67],
    [45,78]
])

In [28]:
for i in cricket:
    print(i)

[23 56]
[33 67]
[45 78]


In [32]:
for i in np.nditer(cricket):
    print(i)

23
56
33
67
45
78


In [33]:
height

array([23, 45, 67, 89])

In [34]:
weight=np.array([34,55,23,45])

In [35]:
bmi=weight/height**2

In [38]:
for i in bmi:
    print(i)

0.06427221172022685
0.027160493827160494
0.0051236355535754065
0.005681100871102134


In [39]:
meas=np.array([height,weight])

In [40]:
for i in meas:
    print(i)

[23 45 67 89]
[34 55 23 45]


## 6.DataFrame

In [41]:
import pandas as pd

In [44]:
df=pd.read_csv("E:\datasets\cars.csv",index_col=0)

In [45]:
df

cars_per_cap        country  drives_right
US            809  United States          True
AUS           731      Australia         False
JAP           588          Japan         False
IN             18          India         False
RU            200         Russia          True
MOR            70        Morocco          True
EG             45          Egypt          True

In [46]:
for i in df:
    print(i)

cars_per_cap
country
drives_right


In [48]:
for lab,row in df.iterrows():
    print(lab)
    print(row)

US
cars_per_cap              809
country         United States
drives_right             True
Name: US, dtype: object
AUS
cars_per_cap          731
country         Australia
drives_right        False
Name: AUS, dtype: object
JAP
cars_per_cap      588
country         Japan
drives_right    False
Name: JAP, dtype: object
IN
cars_per_cap       18
country         India
drives_right    False
Name: IN, dtype: object
RU
cars_per_cap       200
country         Russia
drives_right      True
Name: RU, dtype: object
MOR
cars_per_cap         70
country         Morocco
drives_right       True
Name: MOR, dtype: object
EG
cars_per_cap       45
country         Egypt
drives_right     True
Name: EG, dtype: object


Selec

In [49]:
for lab,row in df.iterrows():
    print(lab +":"+ row["country"])

US:United States
AUS:Australia
JAP:Japan
IN:India
RU:Russia
MOR:Morocco
EG:Egypt


In [51]:
df.index

Index(['US', 'AUS', 'JAP', 'IN', 'RU', 'MOR', 'EG'], dtype='object')

In [52]:
df.columns

Index(['cars_per_cap', 'country', 'drives_right'], dtype='object')

In [53]:
df.values

array([[809, 'United States', True],
       [731, 'Australia', False],
       [588, 'Japan', False],
       [18, 'India', False],
       [200, 'Russia', True],
       [70, 'Morocco', True],
       [45, 'Egypt', True]], dtype=object)